---
dist: trusty
sudo: required

language: python

matrix:
  fast_finish: true

services:
  - docker

env:
  global: # applied to every run
    container_env_lang: en_US.utf-8
    container_env_path: /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
    container_env_term: xterm

    goss_version: "0.3.2"

    role_name: degoss

  matrix: # each entry is its own run
    - { image: "naftulikay/centos-vm:7",      systemd: true }
    - { image: "naftulikay/xenial-vm:latest", systemd: true }
    - { image: "naftulikay/trusty-vm:latest", systemd: false }

install:
  - tests/runc start ${image} ${systemd}
  # display version
  - tests/runc exec ansible --version

script:
  # check syntax
  - tests/runc exec ansible-playbook --syntax-check /etc/ansible/roles/${role_name}/tests/playbook.yml
  # execute degoss without a version
  - tests/runc exec ansible-playbook /etc/ansible/roles/${role_name}/tests/playbook.yml
  # execute degoss with a version
  - tests/runc exec ansible-playbook -e goss_version=${goss_version} /etc/ansible/roles/${role_name}/tests/playbook.yml
  # test and measure failure
  - "tests/fail ansible-playbook \
      -e goss_version=${goss_version} \
      -e should=fail \
      /etc/ansible/roles/${role_name}/tests/playbook.yml"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
