- name: Download goss binaries
  get_url:
    url: 'https://github.com/aelsabbahy/goss/releases/latest/download/{{ item.src }}'
    dest: '{{ goss_binary_dir }}/{{ item.dest }}'
    mode: '0766'
  with_items:
    - { src: 'goss-linux-amd64', dest: 'goss' }
    - { src: 'dgoss', dest: 'dgoss' }