---
- name: create workdir
  command: mktemp -d /tmp/degoss.XXXXXXXXXX
  register: workdir
  changed_when: false

- name: establish facts
  set_fact:
    degoss_tmp_root: "{{ workdir.stdout.strip() }}"
    degoss_test_dir: "{{ workdir.stdout.strip() }}/tests"

- name: create directories
  file: path={{ degoss_test_dir }} state=directory
  changed_when: false

# deploy test files including the main and additional test files
- name: deploy test files
  copy:
    src: |-
      {%- if item.startswith('/') -%}
        {{ item }}
      {%- else -%}
        {{ playbook_dir | default(".") }}/{{ item }}
      {%- endif -%}
    dest: "{{ degoss_test_dir }}"
    mode: 0644
    directory_mode: 0755
    setype: user_tmp_t
  with_items: "{{ [goss_file] + goss_addtl_files + goss_addtl_dirs }}"
  changed_when: false

# run the tests
- name: run tests
  degoss:
    clean: "{{ degoss_clean }}"
    clean_on_failure: "{{ degoss_clean_on_failure }}"
    debug: "{{ degoss_debug }}"
    facts: "{{ ansible_facts | to_json }}"
    test_dir: "{{ degoss_test_dir }}"
    test_file: "{{ goss_file }}"
    tmp_root: "{{ degoss_tmp_root }}"
    variables: "{{ goss_variables | default({}) | to_json }}"
